In [2]:
from IPython.display import set_matplotlib_formats
set_matplotlib_formats('svg')

# Python et le calcul numérique

-----------------------------------------

***Basile Marchand (Centre des Matériaux - Mines ParisTech/CNRS/Université PSL)***

## Module Python pour le calcul numérique

Nous l'avons vu dans les parties précédentes nous pouvons déjà réaliser un certain nombre de choses en Python et automatiser un grand nombre d'action via des programmes. Cependant il manque encore quelques éléments pour satisfaire à tous les besoins du mécanicien. Parmis ces éléments manquants il y a le calcul numérique. En effet, nous avons vu que de nativement Python sait faire du calcul mais cela n'est pas suffisant, il manque en effet les notions de matrices, vecteurs. Un autre manque, qui sera comblé je vous rassure, est une librairie de fonctions prêtes à l'emploi pour l'intégration, les problèmes d'optimisation, ... 

C'est ce point que nous allons aborder dans le cours aujourd'hui au travers de deux modules incontournables : 
* [`NumPy`](www.numpy.org) : module Python permettant de travailler avec des tableaux multidimensionnels (vecteur, matrice et plus). Il définit également un certain nombre d'opérations mathématiques pouvant travailler directement avec ces tableaux. 
* [`SciPy`](www.scipy.org) : module Python disposant de nombreuses fonctionnalité en terme de calcul numérique ayant pour finalitée d'offrir à l'utilisateur un environnement de calul scientifique semblable à ceux de logiciels spécialisés tel que Matlab, Octave ou Scilab. 



## Numpy 

Comme dit en introduction NumPy est un module Python permettant de travailler avec des tableaux multidimensionel. Pour preuve de la souplesse de ce module ainsi que de ses bonnes performances il faut souligner qu'il s'agit du module qui est employé à peu prêt dans tous les autres modules scientifiques disponibles dans Python. Le secret du module NumPy est que par un soucis de performances ce dernier n'est pas développer en Python mais en C++. 

Bien évidemment l'utilisation de ce module se fait de la manière classique : 

```python
import numpy
```

Cependant par soucis de simplicité vous verrez quasiment toujours l'import réalisé en donnant un alias à numpy  :

```python
import numpy as np
```

L'objet de base dans NumPy, celui que l'on va manipuler par la suite, est le **array**. Un **array** numpy est un tableau multidimensionnel de même type (on ne peut pas mélanger entier, flottant et chaine de caractère dans un même **array** par exemple). On appelle *rang* de l'**array** le nombre de dimension de ce dernier : 
* *rang de 1* : tableau à 1 dimension donc une ligne de M colonnes
* *rang de 2* : tableau à 2 dimension donc N lignes et M colonnes
* *rang de 3* : tableau à trois dimensions (un pavé dans l'espace) 
* etc 

Et la forme de l'*array*, *shape* en anglais, est un N-uplet qui caractérise la taille du tableau suivant chacune de ses dimensions. Par exemple :
* Un vecteur ligne de taille **N** correspond à un **array** avec rank=1 et shape=(N,)
* Un vecteur colonne de taille **N** correspond à un **array** avec rank=2 et shape=(1,N)
* Une matrice rectangulaire **NxM** correspond à un **array** avec rank=2 et shape=(N,M)
* Une hypermatrice carré **NxNxN** correspond à un array avec rank=3 et shape=(N,N,N)


### Création d'un **array**

La définition d'un **array** à partir d'un ensemble de valeurs se fait de la manière suivante : 

In [1]:
import numpy as np
une_matrice_3_3 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("une matrice 3x3 : \n{}".format(une_matrice_3_3))
un_vecteur_colonne = np.array([[1,], [2,], [3,]]) 
print("un vecteur colonne : \n{}".format(un_vecteur_colonne))
un_vecteur_ligne = np.array([1,2,3])
print("un vecteur ligne : \n{}".format(un_vecteur_ligne))
un_tableau_3_dimension = np.array( [[[1,2,3],[2,5,6]], [[11,12,13],[14,15,16]]])
print("un tableau 3 dimension :\n{}".format(un_tableau_3_dimension))

une matrice 3x3 : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
un vecteur colonne : 
[[1]
 [2]
 [3]]
un vecteur ligne : 
[1 2 3]
un tableau 3 dimension :
[[[ 1  2  3]
  [ 2  5  6]]

 [[11 12 13]
  [14 15 16]]]


In [4]:
forme = un_vecteur_colonne.shape 
rang  = len(un_vecteur_colonne.shape)
print("shape = {}".format(forme))
print("rank  = {}".format(rang))


shape = (3, 1)
rank  = 2


Afin d'initialiser un **array** NumPy dispose d'un certain nombre de fonction permettant de créer des tableaux. 
* `np.zeros` qui permet de créer un tableau ne contenant que des zéros
* `np.zeros_like` qui permet de construire une matrice de zéros ayant la même forme qu'une autre matrice donnée en entrée.
* `np.ones` qui créé un tableau ne contenant que des uns.
* `np.eye` qui créé un tableau identité
* `np.random.rand` qui créé une matrice comptenant des valeurs aléatoires.

Ci-dessous des exemples d'utilisation de chacune de ces fonctions. 

In [5]:
print("np.zeros")
print(np.zeros((2,4)))
print("np.ones")
print(np.ones((5,1)))
print("np.zeros_like")
m = np.ones((2,3))
print(np.zeros_like(m))
print("np.eye")
print(np.eye(4))
print("np.random.rand")
print(np.random.rand(3,5))

np.zeros
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
np.ones
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
np.zeros_like
[[0. 0. 0.]
 [0. 0. 0.]]
np.eye
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
np.random.rand
[[0.01241999 0.47160465 0.2573368  0.8838361  0.39037009]
 [0.93871722 0.75789297 0.37360782 0.77687475 0.24318307]
 [0.57244805 0.87377082 0.25741403 0.40909682 0.47682399]]


### Manipulation des **array**


La manipulation des **array** NumPy et notamment l'accès aux valeurs contenues dans ce dernier se fait dans le même esprit que l'accès aux éléments d'une liste à la différence près que l'on doit spécifier pour un **array** plusieurs indices étant donné qu'il s'agit d'un tableau multidimensionnel. 

> **Attention :**  
> Comme pour les listes et tuples la numérotation des indices commence à **0**

In [6]:
un_tableau = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print("Le tableau : \n{}".format(un_tableau))

a_12 = un_tableau[1,2]
print("Element 1,2 : {}".format(a_12))

a_1all = un_tableau[1,:]
print("Element 1,all : {}".format(a_1all))

Le tableau : 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Element 1,2 : 8
Element 1,all : [ 6  7  8  9 10]


Tout comme pour les listes on peut accéder à des portions du tableau à l'aide de la notation `start:next+1:step`

In [7]:
sub_array = un_tableau[1:,1:]
print(sub_array)

[[ 7  8  9 10]
 [12 13 14 15]]


In [8]:
sub_array = un_tableau[0,:]
print(sub_array)

[1 2 3 4 5]


In [9]:
sub_array = un_tableau[::2,::2]
print(sub_array)

[[ 1  3  5]
 [11 13 15]]


Ainsi il est possible de cette manière d'accéder à un sous-tableau. Cependant dans les applications, typiquement le calcul éléments finis, il est nécessaire d'avoir accès a un sous-tableau, souvent discontinu, uniquement à partir de liste d'indices de lignes et de colonnes. Or si l'on fait ca directement on peut observer ci-dessous que le sous-tableau extrait ne correspond pas. 

In [10]:
matrice_a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print("La matrice complète : \n{}".format(matrice_a))
idx_i = [0,2]
idx_j = [1,4]
sous_matrice = matrice_a[idx_i, idx_j]
print("La sous-matrice par la mauvaise approche : \n{}".format(sous_matrice))

La matrice complète : 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
La sous-matrice par la mauvaise approche : 
[ 2 15]


Afin d'avoir le résultat souhaité il est nécessaire d'utiliser la fonction `np.ix_`. Cette dernière permet de générer à partir de deux listes d'indices, le **mask** de valeurs souhaitées. 

In [11]:
matrice_a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print("La matrice complète : \n{}".format(matrice_a))
idx_i = [0,2]
idx_j = [1,4]
sous_matrice = matrice_a[np.ix_(idx_i, idx_j)]
print("La sous-matrice par np.ix_ : \n{}".format(sous_matrice))

La matrice complète : 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
La sous-matrice par np.ix_ : 
[[ 2  5]
 [12 15]]


On vient donc de voir que l'on peut facilement extraire des sous-tableaux mais bien évidemment à l'aide de cela on peut facilement insérer des valeurs par bloque au sein d'un tableau de plus grande dimension. Par exemple : 

In [12]:
big_array = np.zeros((6,6))
little_array = np.eye(3)
print("Big array : \n{}".format(big_array))
print("Little array : \n{}".format(little_array))
big_array[3:,0:3] = little_array
print("Big array après insertion : \n{}".format(big_array))
little_array = np.random.rand(2,2)
big_array[np.ix_([1,3],[1,3])] = little_array
print("Big array après insertion: \n{}".format(big_array))

Big array : 
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Little array : 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Big array après insertion : 
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
Big array après insertion: 
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.83817005 0.         0.19723512 0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [1.         0.88205628 0.         0.79069731 0.         0.        ]
 [0.         1.         0.         0.         0.         0.        ]
 [0.         0.         1.         0.         0.         0.        ]]


Parmi les autres manipulations possibles sur les **array** NumPy il y a l'opération `reshape` qui permet de changer la forme d'un tableau. Par exemple : 

In [13]:
array_1 = np.array([[1,2,3],[4,5,6]])
print("Tableau avant reshape {} : \n{}".format( array_1.shape, array_1))

array_2 = array_1.reshape((6,1))
print("Tableau après reshape {} : \n{}".format( array_2.shape, array_2))

array_3 = array_1.reshape((6,))
print("Tableau après reshape {} : \n{}".format( array_3.shape, array_3))


Tableau avant reshape (2, 3) : 
[[1 2 3]
 [4 5 6]]
Tableau après reshape (6, 1) : 
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
Tableau après reshape (6,) : 
[1 2 3 4 5 6]


> **Attention :**  
> Pour que l'opération de reshape puisse fonctionner il est impératif que le nombre d'éléments total soit préserver. C'est à dire qu'il faut impérativement que le produit des tailles suivant chacunes des dimensions soit égale avant et après le `reshape`

> *Astuce :*  
> Pour plus de simplicité vous pouvez lors de l'opération de reshape, laisser une des tailles libre. Cette dernière sera automatiquement déduite des autres afin de satisfaire à la condition de conservation du nombre d'élément. Pour cela il suffit de donner une taille de **-1** à la dimension laissée libre.

In [14]:
vecteur_colonne = array_1.reshape((-1,1))
print("Après le reshape((-1,1)) : \n{}".format(vecteur_colonne))

Après le reshape((-1,1)) : 
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


### Opérations mathématiques sur les **array**

A présent que nous savons comment définir et manipuler des **array** nous allons comment calculer avec. Car comme dit plus haut le principal intérêt de NumPy est de pouvoir définir des tableau multi-dimensionnel et surtout de calculer avec. 

Tout d'abord les opérations usuelles, somme, addition, multiplication et division sont définies entre deux **array** mais également entre un **array** et un **nombre**. 


In [15]:
array_1 = np.array([[1,2,3], [4,5,6]])
array_2 = np.array([[0,1,0],[1,0,1]])

## Somme d'un array un d'un nombre
res = array_1 + 1.
print( res )
## Somme de deux array
res = array_1 + array_2
print( res )
## Soustraction d'un array et d'un nombre
res = array_1 - 1.
print( res )
## Soustraction de deux array 
res = array_1 - array_2
print( res )
## Multiplication d'un array et d'un nombre
res = 2. * array_1
print( res )
## Multiplication terme à terme de deux array
res = array_1 * array_2
print( res )
## Division d'un array par un nombre
res = array_1 / 2. 
print( res )
## Division d'un nombre par un array 
res = 1./array_1
print( res )
## Division terme à terme de deux array
res = array_2 / array_1 
print( res )

[[2. 3. 4.]
 [5. 6. 7.]]
[[1 3 3]
 [5 5 7]]
[[0. 1. 2.]
 [3. 4. 5.]]
[[1 1 3]
 [3 5 5]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[0 2 0]
 [4 0 6]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[0.         0.5        0.        ]
 [0.25       0.         0.16666667]]


> **Attention :**  
> Les opérations de division et surtout de multiplication entre deux **array** sont des opérations **terme à terme** !!
> Il ne s'agit pas de la multiplication au sens matricielle du terme. 

Comment fait on un vrai produit matriciel alors ? C'est la question qui vous démange j'en suis sur !! Pas d'inquiétude le produit matriciel tel que vous l'avez vu en math existe bien dans NumPy. Pour écrire le produit matriciel de deux tableaux NumPy vous pouvez procéder de la manière suivante : 

```python 
res = array_1.dot( array_2 )
```

Cette notation et le fait que l'opérateur `*` soit le produit terme à terme est l'un des principaux reproches fait à la librairies NumPy notamment de la part des utilisateur venant du monde Matlab. Pour cette raison depuis Python version 3.5 il a été ajouté à numpy l'opérateur `@` qui permet de faire le produit matriciel entre deux tableaux. 

```python
res = array_1 @ array_2
```

In [16]:
array_1 = np.array([[1,2,3],[4,5,6]])
array_2 = np.array([[10,20],[30,40],[50,60]])
print('array_1 = \n{}'.format(array_1))
print('array_2 = \n{}'.format(array_2))

res_1 = array_1.dot( array_2 )
## ou 
res_2 = array_1 @ array_2

print("res_1 = array_1.dot(array_2) = \n{}".format(res_1))
print("res_2 = array_1 @ array_2 = \n{}".format(res_2))

array_1 = 
[[1 2 3]
 [4 5 6]]
array_2 = 
[[10 20]
 [30 40]
 [50 60]]
res_1 = array_1.dot(array_2) = 
[[220 280]
 [490 640]]
res_2 = array_1 @ array_2 = 
[[220 280]
 [490 640]]


### Quelques opérations utiles 

En plus des opérations usuelles, NumPy offre un certain nombre de fonctions additionnelles permettant de travailler directement sur les **array**.  

Parmis ces différentes fonctions on retrouve tout d'abord toutes les fonctions définit pur les nombre dans le module `math` mais pouvant ici s'appliquer à des tableaux multi-dimensionnels. Par exemple : 

In [17]:
array_1 = np.array([[1,2,3],[4,5,6]])
res = np.log(array_1)
print(res)

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [18]:
res = np.cos( np.deg2rad( 10 * array_1 ) )
print( res )

[[0.98480775 0.93969262 0.8660254 ]
 [0.76604444 0.64278761 0.5       ]]


Il y a également quelques opérations plus spécifiques aux tableaux, comme : 
* `mean` calcul de la moyenne
* `std` écart-type
* `max` valeur max
* `min` valeur min

In [19]:
val_max_tableau = array_1.max()
print(val_max_tableau)
### Recherche du n-uplet max selon la dimension 1
### donc recherche de la colonne max
val_max = array_1.max(1)
print("Colonne max : {}".format(val_max))
### Recherche du n-uplet max selon la dimension 0
### donc recherche de la ligne max
val_max = array_1.max(0)
print("Ligne max : {}".format(val_max))

6
Colonne max : [3 6]
Ligne max : [4 5 6]


Bien entendu les mêmes modes de fonctionnement sont disponibles pour les fonctions min, mean, std.

#### Les tests et opérations booléennes

Une fonctionnalité très puissante et très utile de NumPy est la gestion des tests et des opérations booléenne. En effet cela permet facilement d'extraire des sous-matrices, de trier des données, ... La syntaxe est exactement la même que pour les opérations sur les nombres sauf pour les instructions `and` et `or` qui doivent être remplacée par `np.logical_and` et `np.logical_or`. Par exemple réalisons quelques opérations sur un tableau aléatoire. 


In [20]:
tab_random = np.random.rand(5,6)
print( tab_random )

[[0.50440161 0.60517839 0.7117132  0.4891493  0.53560473 0.98282014]
 [0.59497632 0.73737505 0.84476391 0.39460153 0.48803134 0.17228741]
 [0.96097354 0.91307354 0.6319802  0.15482494 0.30407224 0.0806149 ]
 [0.62741203 0.34740305 0.97932308 0.59943706 0.97122529 0.46022487]
 [0.99696404 0.316279   0.84163091 0.28752257 0.8340381  0.48369349]]


In [21]:
mask = tab_random < 0.5 
print(mask)

[[False False False  True False False]
 [False False False  True  True  True]
 [False False False  True  True  True]
 [False  True False False False  True]
 [False  True False  True False  True]]


L'object `mask` est un **array** NumPy de la même taille que le tableau testé, ici `tab_random`, de booléen correspondant au résultat du test effectué sur chacun des termes du tableau. Pour extraire le tableau résultant il suffit tout simplement de procéder de la manière suivante : 

In [22]:
tab_rand_inf_05 = tab_random[mask]
print( tab_rand_inf_05 )

[0.4891493  0.39460153 0.48803134 0.17228741 0.15482494 0.30407224
 0.0806149  0.34740305 0.46022487 0.316279   0.28752257 0.48369349]


Si l'on souhaite maintenant récupérer toutes les valeurs comprises entre 0.4 et 0.6 il suffit de procéder de la manière suivante : 

In [23]:
mask = np.logical_and ( tab_random < 0.6, tab_random > 0.4 ) 
print(mask)
tab_rand_inf_sup = tab_random[mask]
print( tab_rand_inf_sup )

[[ True False False  True  True False]
 [ True False False False  True False]
 [False False False False False False]
 [False False False  True False  True]
 [False False False False False  True]]
[0.50440161 0.4891493  0.53560473 0.59497632 0.48803134 0.59943706
 0.46022487 0.48369349]


### L'algèbre linéaire

En plus des opérations usuelles et des opérations booléennes NumPy implémente un certain nombre de fonctions d'algèbre linéaire. En effet car NumPy étant le module Python pour les tableaux multi-dimensionnel et donc en particulier les matrices et les vecteurs, il devait impérativement disposer des ces fonctions d'algèbre linéaire. Pour utiliser les fonctions d'algèbre linéaire de NumPy il faut faire appel au sous-module `numpy.linalg`. 

In [24]:
import numpy.linalg as npl

Tout d'abord il y a les fonctions `norm`, `cond` et `det`, qui comme leurs noms l'indiquent permettent de calculer respectivement la norme, le conditionnement et le déterminant d'un tableau à 2 dimensions. 

In [25]:
array_2d = np.random.rand(5,5)
norm_array = npl.norm( array_2d )
cond_array = npl.cond( array_2d )
det_array  = npl.det( array_2d )


print("A = \n{}".format(array_2d))
print("||A||   = {}".format(norm_array))
print("cond(A) = {}".format(cond_array))
print("det(A)  = {}".format(det_array))

A = 
[[0.40359057 0.08415542 0.46081428 0.3125961  0.47703485]
 [0.81075711 0.21071153 0.16879296 0.87783853 0.10928041]
 [0.18657027 0.97411044 0.27697113 0.27998399 0.77797036]
 [0.21988741 0.06797509 0.3078343  0.91150968 0.46662265]
 [0.55777479 0.75015237 0.22990774 0.17076016 0.97418755]]
||A||   = 2.6581227419711815
cond(A) = 11.667025623644054
det(A)  = 0.11715355284034291


Il y a ensuite toutes les méthodes de décomposition de matrice et de résolution de systèmes linéaires :
* `solve( A, b )` qui permet de trouver la solution au système $A\cdot x = b$
* `inv( A )` qui permet de calculer $A^{-1}$
* `pinv( A )` qui calcul la pseudo inverse de la matrice $A$
* `svd` qui permet de calculer la décomposition en valeur singulière d'une matrice
* `eig( A )` calcul les valeurs et vecteurs propres 

In [26]:
rhs = np.random.rand(5,1)
print("rhs = \n{}".format(rhs))
x = npl.solve( array_2d, rhs )
print("Solution x = \n{}".format(x))
verif = array_2d.dot( x ) - rhs
print("A.x-rhs = \n{}".format(verif))
array_inv = npl.inv( array_2d )
verif = array_inv.dot( array_2d )
print("inv(A)*A = \n{}".format( verif ) )


rhs = 
[[0.42579873]
 [0.36464957]
 [0.91929189]
 [0.38330078]
 [0.69369916]]
Solution x = 
[[-0.03174012]
 [ 0.71431891]
 [ 0.7540054 ]
 [ 0.13083973]
 [-0.02067252]]
A.x-rhs = 
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 1.11022302e-16]
 [ 0.00000000e+00]
 [-1.11022302e-16]]
inv(A)*A = 
[[ 1.00000000e+00  4.80260566e-17  9.07099375e-17  2.42665868e-16
  -5.37714040e-17]
 [-3.36665995e-17  1.00000000e+00  1.63924985e-17 -2.58820351e-18
  -3.48986059e-17]
 [-3.75316730e-17  7.16669173e-17  1.00000000e+00 -5.78638624e-17
   3.11837390e-16]
 [ 3.70311706e-17  4.86459437e-17  1.21384119e-17  1.00000000e+00
   8.88860099e-17]
 [ 4.64223634e-17 -1.47401886e-17 -4.29951649e-18 -4.36734148e-17
   1.00000000e+00]]


### Les entrées-sorties avec NumPy



En plus de fournir des fonctionnalité de création et manipulations de tableaux et d'algèbre linéaire NumPy permet de gérer des entrées-sorties de manière plus simples pour l'utilisateur que ce qui est permis de base dans Python. 

Parmis les différentes fonctions d'IO que propose NumPy, les trois qui vous seront certainement le plus utile sont : 
* `loadtxt` qui permet de charger le contenu d'un fichier texte (bien formatté, par exemple un csv) sous la forme directement sous la forme d'un tableau NumPy. 
* `savetxt` permet de sauvegarder dans un fichier texte le contenu d'un `array` numpy. 
* `genfromtxt` similaire à `loadtxt` sauf qu'ici le fichier de données peut comporter des trous, données manquantes, qui seront alors automatiquement remplacée par une valeur spécifiée par l'utilisateur. 




Voici ci dessous un extrait d'un fichier texte contenant des données d'acquisition d'essai de traction.

In [27]:
!head data/curves/data.txt

Pour charger ces données la première solution serait de parser le fichier à la main en utilisant `open`, `read` et enfin la méthode `split` des string. Cependant `numpy` met à disposition la méthode `loadtxt` qui offre un confort d'utilisation accru. Par exemple pour charger les données précédentes, cela se réalise en une seule commande : 

In [28]:
data_from_file = np.loadtxt("data/curves/data.txt", comments="#")

In [29]:
print("Shape : {} ".format(data_from_file.shape))
print( data_from_file[:10,:])

Shape : (681, 4) 
[[ 1.1914063e-01  1.5440350e-03  9.7813249e-02  7.4900000e-05]
 [ 2.1875000e-01  7.2182400e-04  9.9797331e-02  1.9703100e-04]
 [ 3.1835938e-01  1.8643150e-03  1.0510900e-01  1.1768200e-04]
 [ 4.1796875e-01  8.7479400e-04  1.0612570e-01  1.2647400e-04]
 [ 5.1757813e-01  1.5392550e-03  1.1434808e-01  1.3466900e-04]
 [ 6.1718750e-01  5.5929400e-04  1.1795573e-01  1.7449300e-04]
 [ 7.1679688e-01  1.1329300e-03  1.3211440e-01  2.2992500e-04]
 [ 8.1640625e-01  2.5813600e-04  1.4328328e-01 -4.4100000e-05]
 [ 9.1601563e-01  8.1265000e-04  1.6090605e-01  4.2073400e-04]
 [ 1.0156250e+00 -4.4934800e-04  1.8887568e-01  2.5969000e-04]]


On remarque que l'on a spécifié l'argument optionel `comments`, cela permet d'indiquer à NumPy quelles lignes sont à ne pas prendre en compte. Si jamais les premières lignes ne commencent pas par un caractère spécifique (carctère de commentaire) il est quand même possible de les ignorer à l'aide de l'argument optionel `skiprosws` qui permet d'indiquer le nombre que l'on souhaite ignorer au début du fichier. Une utilisation équivalente de `loadtxt` à la précédente serait donc : 

In [30]:
data_from_file = np.loadtxt("data/curves/data.txt", skiprows=5)

In [31]:
print("Shape : {} ".format(data_from_file.shape))
print( data_from_file[:10,:])

Shape : (681, 4) 
[[ 1.1914063e-01  1.5440350e-03  9.7813249e-02  7.4900000e-05]
 [ 2.1875000e-01  7.2182400e-04  9.9797331e-02  1.9703100e-04]
 [ 3.1835938e-01  1.8643150e-03  1.0510900e-01  1.1768200e-04]
 [ 4.1796875e-01  8.7479400e-04  1.0612570e-01  1.2647400e-04]
 [ 5.1757813e-01  1.5392550e-03  1.1434808e-01  1.3466900e-04]
 [ 6.1718750e-01  5.5929400e-04  1.1795573e-01  1.7449300e-04]
 [ 7.1679688e-01  1.1329300e-03  1.3211440e-01  2.2992500e-04]
 [ 8.1640625e-01  2.5813600e-04  1.4328328e-01 -4.4100000e-05]
 [ 9.1601563e-01  8.1265000e-04  1.6090605e-01  4.2073400e-04]
 [ 1.0156250e+00 -4.4934800e-04  1.8887568e-01  2.5969000e-04]]
